String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Veggies!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a fork of <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a>, which is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Veggie Icons by <a href=\"https://symbolicons.com/\">Symbolicons</a> were created by <a href=\"http://twitter.com/sensibleworld\">Jory Raphael</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-Veggies #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'cabbage',
    '%4'                    : 'cucumber',
    '%8'                    : 'tomato',
    '%16'                   : 'carrot',
    '%32'                   : 'pepper',
    '%64'                   : 'onion',
    '%128'                  : 'corn',
    '%256'                  : 'parsley',
    '%512'                  : 'potato',
    '%1024'                 : 'yellow squash',
    '%2048'                 : 'radish',
    '%4096'                 : 'pumpkin',
    '%8192'                 : 'chard',
    '%p0'                   : 'cabbage',
    '%p4'                   : 'cucumber',
    '%p8'                   : 'tomato',
    '%p16'                  : 'carrot',
    '%p32'                  : 'pepper',
    '%p64'                  : 'onion',
    '%p128'                 : 'corn',
    '%p256'                 : 'parsley',
    '%p512'                 : 'potato',
    '%p1024'                : 'yellow squash',
    '%p2048'                : 'radish',
    '%p4096'                : 'pumpkin',
    '%p8192'                : 'chard'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Veggies!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a fork of <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a>, which is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Veggie Icons by <a href=\"https://symbolicons.com/\">Symbolicons</a> were created by <a href=\"http://twitter.com/sensibleworld\">Jory Raphael</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-Veggies #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'cabbage',
    '%4'                    : 'cucumber',
    '%8'                    : 'tomato',
    '%16'                   : 'carrot',
    '%32'                   : 'pepper',
    '%64'                   : 'onion',
    '%128'                  : 'corn',
    '%256'                  : 'parsley',
    '%512'                  : 'potato',
    '%1024'                 : 'yellow squash',
    '%2048'                 : 'radish',
    '%4096'                 : 'pumpkin',
    '%8192'                 : 'chard',
    '%p0'                   : 'cabbage',
    '%p4'                   : 'cucumber',
    '%p8'                   : 'tomato',
    '%p16'                  : 'carrot',
    '%p32'                  : 'pepper',
    '%p64'                  : 'onion',
    '%p128'                 : 'corn',
    '%p256'                 : 'parsley',
    '%p512'                 : 'potato',
    '%p1024'                : 'yellow squash',
    '%p2048'                : 'radish',
    '%p4096'                : 'pumpkin',
    '%p8192'                : 'chard'
  }

});
